### PR TITLE
MAIN Add.rxjs6.adapter

### PR DESCRIPTION
**Pull request by herman-rogers**

### CODE REVIEW

**Comment by lanwen** [comment]
why not just add one?

**Comment by herman-rogers** [comment]
Sorry what do you mean?

**Comment by lanwen** [comment]
Discussed already - but the main point is that it can just add v6 without removing anything and switch to the v6 in our services

**Comment by paschalidi** [comment]
Hey all, @herman-rogers @lanwen can we please close that? I need it for another project.

**Comment by lanwen** [comment]
@paschalidi you can just finish this one https://github.com/bsideup/rx-connect/pull/10 in the way Sergei suggested

**Pull request closed without merging**
